import streamlit as st

st.set_page_config(
    layout="wide"   
)

st.title("🧳Things to Carry")

st.divider()

st.toggle("Shoes")
st.toggle("Slippers")
st.toggle("Sandals")
st.toggle("Corporate Credit Cards")
st.toggle("Personal Credit Cards")
st.toggle("Debit Cards")
st.toggle("Cash")
st.toggle("Digital Wallet")
st.toggle("Powerbank")
st.toggle("Earphones")
st.toggle("Camera")
st.toggle("Side Bag")
st.toggle("Tickets")
st.toggle("Digiyatra")
st.toggle("Passport")
st.toggle("Bag")
st.toggle("Underwear")
st.toggle("T-Shirts")
st.toggle("Shirts")
st.toggle("Formal Pants")
st.toggle("Track Pants")
st.toggle("Jeans")
st.toggle("Raincoat")
st.toggle("Winter Jackets")
st.toggle("Towels")
st.toggle("Swimming Trunks")
st.toggle("Hair Oil")
st.toggle("handkerchief")
st.toggle("Socks")
st.toggle("Masks")
st.toggle("Toothbrush and Paste")
st.toggle("Umbrella")
st.toggle("Watch")
st.toggle("Spectacle Box")
st.toggle("Mobile + Charger")
st.toggle("Medicine")
st.toggle("Food")
st.toggle("Water Bottle")
st.toggle("AADHAAR Card")
st.toggle("PAN Card")
st.toggle("Office IDs")
st.toggle("House Keys")
st.toggle("Goggles")
st.toggle("Driving License + Documents")
st.toggle("Extra Polythene Bags")
st.toggle("Newspapers")
st.toggle("Laptop + Charger")
